GET  http://localhost:3001/usertasks?username="sateesh"

###
POST  http://localhost:3001/adduser/
Content-Type: application/json

{
     "username":"sateesh"
}
###
POST  http://localhost:3001/addtask/
Content-Type: application/json

{
    "taskname":"Finalize THINGS",
     "ischeckes":"false",
     "username":"sateesh"
}

###
PUT http://localhost:3000/taskstatuschange/taskid
###

PUT http://localhost:3000/taskdelete/taskid

